### ISSUE TITLE
`awakeFromNib` Not Properly Handling Multiple Calls

### ISSUE THREAD

**Issue by ghost** [ustwo/baseview-swift#5]
`BaseView` does not properly handle `awakeFromNib` potentially being called more than once. This could lead to crashes by or strange side effects from repeated setup of subviews.
- [Apple Documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSObject_UIKitAdditions/#//apple_ref/occ/instm/NSObject/awakeFromNib)
- [StackOverflow Examples](http://stackoverflow.com/questions/11585956/why-is-awakefromnib-being-called-twice-when-loading-nib-in-nib)

**Comment by madhikarma** [comment]
Hmm I haven't seen this in the wild (repeated calls to awakeFromNib), when I used to use Interface Builder back in iOS 5, but the setup I did there was more configuration based e.g. fonts and colours and also this has not been recently with IB (since we pretty much all switched to building views in code so it can be more custom)

###### Possible Solutions
1. Remove `awakeFromNib` and keep the setup routine to initialisation only 
2. Added some logic to track whether `setup` has been called e.g. `private(set) var isSetup`
3. ...

I prefer solution 1 since it keeps the code cleaner, what do you think? Is there another solution that you like?

**Comment by ghost** [comment]
I prefer solution 2. While you and I both prefer to create interfaces programmatically, others may not. I feel it is still a worthwhile function to keep in the framework.

@danieladias Thoughts on this issue?

**Comment by danieladias** [comment]
@aamctustwo @madhikarma maybe it helps if we define the purpose of setup. I always associated it with creating views programmatically. What could be a use case for views using nibs? Changing colors and fonts or adding more views or do we want to keep it free?

**Comment by ghost** [comment]
@danieladias @madhikarma 

I use the `setup()` function for all of the following:
- Instantiate subviews
- Add subviews to their superview
- Set default properties of the view/subviews

Basically, it makes the view ready for use aside from layout and accessibility setup. I also like putting the default properties in there to remove as much of the presentation code from the controller as makes sense. It also allows the view to be shown and tested from a UI perspective without fully implementing the controller.

**Comment by danieladias** [comment]
@aamctustwo makes total sense but then doesn't it mean that it should be the people to take care of multiple calls (just asking, not sure of my opinion yet). Doesn't this mean that if they are using nibs they will do setup of properties of the views and maybe check if the view is added before adding another? Like Shagun said I have never seen this happen before so not sure.

**Comment by ghost** [comment]
@danieladias I guess it depends on how much they want to use InterfaceBuilder.

If they're using InterfaceBuilder to just layout to "big" items and flow for the app and create/setup the remaining subviews programmatically, then they'd probably want it in `awakeFromNib` but only called once.

If they're using InterfaceBuilder to do all the setup, then `BaseView.swift` probably isn't very useful to them in the first place.

**Comment by danieladias** [comment]
@aamctustwo Yes, I see what you mean. I haven't been using IB for some time now. Does it allow to do everything now? I remember a time we had to do some stuff via code.

From this point of view, solution 2 seems more clear and clean. Removing the call from awakeFromNib just removes functionality :-1:

**Comment by ghost** [comment]
@danieladias IB allows you to do virtually everything regarding setup, layout, and accessibility now. Since they added the `IBInspectable` and `IBDesignable`, even 3rd party or custom views can have their properties adjustable and visible in real-time in IB. 

http://nshipster.com/ibinspectable-ibdesignable/

**Comment by danieladias** [comment]
Yes I remember trying that out when it came out. Thank you @aamctustwo.
